kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}
rules:
- apiGroups:
  - jenkins.io
  resources:
  - pipelineactivities
  - pipelinestructures
  - sourcerepositories
  - environments
  verbs:
  - create
  - list
  - update
  - get
  - watch
  - patch
- apiGroups:
  - jenkins.io
  resources:
  - apps
  - plugins
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineresources
  - tasks
  - pipelines
  - pipelineruns
  verbs:
  - create
  - list
  - get
  - update
