kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "tide.name" . }}
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - apps
      - environments
      - pipelineactivities
      - sourcerepositories
      - pipelinestructures
    verbs:
      - create
      - get
      - edit
      - update
      - patch
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineresources
      - tasks
      - pipelines
      - pipelineruns
    verbs:
      - create
      - list
      - get
      - update
      - watch
      - patch
      - delete
