{{- if .Values.tide.githubApp.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tide-githubapp-tokens
data:
  username: {{ default "jenkins-x[bot]" .Values.tide.githubApp.username | b64enc | quote }}
{{- end }}
