apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tide.name" . }}
  labels:
    app: {{ template "tide.name" . }}
spec:
  replicas: {{ .Values.tide.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "tide.name" . }}
  template:
    metadata:
{{- if .Values.tide.datadog.enabled }}
      annotations:
        ad.datadoghq.com/tide.logs: '[{"source":"prow","service":"tide"}]'
{{- end }}
      labels:
        app: {{ template "tide.name" . }}
    spec:
      serviceAccountName: {{ template "tide.name" . }}
      terminationGracePeriodSeconds: {{ .Values.tide.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "tide.name" . }}
        image: {{ tpl .Values.tide.image.repository . }}:{{ tpl .Values.tide.image.tag . }}
        imagePullPolicy: {{ .Values.tide.imagePullPolicy }}
{{ if .Values.tide.args }}
        args:
{{ toYaml .Values.tide.args | indent 10 }}
{{- end }}
        ports:
          - name: http
            containerPort: {{ .Values.tide.service.internalPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.tide.probe.path }}
            port: http
          initialDelaySeconds: {{ .Values.tide.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.tide.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.tide.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.tide.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.tide.probe.path }}
            port: http
          periodSeconds: {{ .Values.tide.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.tide.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.tide.readinessProbe.timeoutSeconds }}
        env:
        - name: "GIT_KIND"
          value: "{{ .Values.git.kind }}"
        - name: "GIT_SERVER"
          value: "{{ .Values.git.server }}"
{{- if .Values.tide.githubApp.enabled }}
        - name: "GITHUB_APP_SECRET_DIR"
          value: "/secrets/githubapp/tokens"
{{- else }}
        - name: "GIT_USER"
          value: {{ .Values.user }}
        - name: "GIT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: lighthouse-oauth-token
              key: oauth
{{- end }}
{{- if .Values.tide.env }}
{{- range $pkey, $pval := .Values.tide.env }}
        - name: {{ $pkey }}
          value: {{ $pval }}
{{- end }}
{{- end }}
        resources:
{{ toYaml .Values.tide.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
{{- if .Values.tide.githubApp.enabled }}
        - name: githubapp-tokens
          mountPath: /secrets/githubapp/tokens
          readOnly: true
{{- end }}
      volumes:
      - name: config
        configMap:
          name: config
{{- if .Values.tide.githubApp.enabled }}
      - name: githubapp-tokens
        secret:
          secretName: tide-githubapp-tokens
{{- end }}
    {{- with .Values.tide.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tide.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tide.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
